services:
  proxy:
    build: proxy
    container_name: fproxy
    restart: always
    ports:
      - 81:80
    depends_on:
      - api
    networks:
      - flowers_net

  api:
    build: api
    container_name: fapi
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - 8000:8000
    networks:
      - flowers_net
    volumes:
      - ./api:/app

  rabbitmq:
    build: rabbit
    container_name: frabbit
    ports:
       - 5672:5672
       - 15672:15672
    networks:
      - flowers_net

  consumer:
    build: consumer
    container_name: fconsumer
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - 8001:8001
    networks:
      - flowers_net
    volumes:
      - ./consumer:/app


  influxdb:
    image: influxdb:2.7
    container_name: finfluxdb
    restart: always 
    ports:
      - 8086:8086
    volumes:
      - /home/influxdb2:/var/lib/influxdb2:rw
    networks:
      - flowers_net


networks:
  flowers_net: