services:
  proxy:
    build: proxy
    container_name: fproxy
    restart: always
    ports:
      - 81:80
    depends_on:
      - api
    networks:
      - flowers_net

  api:
    build: api
    container_name: fapi
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - 8000:8000
    networks:
      - flowers_net
    volumes:
      - ./api:/app

  rabbitmq:
    build: rabbit
    container_name: frabbit
    ports:
       - 5672:5672
       - 15672:15672
    networks:
      - flowers_net

  consumer:
    build: consumer
    container_name: fconsumer
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - 8001:8001
    networks:
      - flowers_net
    volumes:
      - ./consumer:/app
    env_file:
      - .env

  influxdb:
    image: influxdb:${INFLUXDB_VERSION}
    container_name: finfluxdb
    restart: always 
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:${DOCKER_INFLUXDB_INIT_PORT}
    volumes:
      - /home/influxdb2:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    networks:
      - flowers_net

  gafana:
    image: grafana/grafana-oss:${GRAFANA_VERSION}
    container_name: fgrafana
    restart: always
    user: '0'
    ports: 
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=mwdev
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - /home/grafana:/var/lib/grafana
    networks:
      - flowers_net


networks:
  flowers_net: